org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.d3f4ul1
archives_base_name=lungeswap

# Dependencies
fabric_api_version=0.141.6+1.21.11
